# -*- coding: utf-8 -*-
"""lab6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vTGElNdLlmRw2gtCaG_u5D9tlgS4vIvz

# HTU GenAI Lab 6 - Mini Project
## Text Summarizer using GitHub Models
"""

!pip install --quiet openai
print("OpenAI client installed.")

from getpass import getpass

GITHUB_TOKEN = getpass("Paste your GitHub PAT (input is hidden): ")
print("Token stored in memory (not printed).")

from openai import OpenAI

# Create client using GitHub Models endpoint
client = OpenAI(
    base_url="https://models.github.ai/inference/v1",
    api_key=GITHUB_TOKEN
)

print("Client created successfully.")

question = "What are the benefits of using GitHub Marketplace Models?"

prompt = f"Answer the following question clearly and concisely:\n\n{question}"

response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "user", "content": prompt}
    ]
)

print("Q:", question)
print("A:", response.choices[0].message.content)

"""## Mini Project: Text Summarizer

This project summarizes any paragraph (Arabic or English) into exactly three concise bullet points.

"""

def summarize_text(text):
    """
    Summarizes a given paragraph (Arabic or English) into
    exactly three short bullet points.
    """
    system_prompt = (
        "You are a helpful assistant that takes any English or Arabic paragraph "
        "and summarizes it into exactly 3 concise bullet points. "
        "Each bullet must be one short sentence. "
        "Do NOT write anything else before or after the bullets."
    )

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": text}
        ]
    )

    return response.choices[0].message.content

paragraph = input("Paste your paragraph to summarize:\n\n")

summary = summarize_text(paragraph)

print("\n--- Summary (3 bullet points) ---\n")
print(summary)

"""## Reflection

During this lab, I learned how to connect Google Colab to GitHub Models using the OpenAI client, run my first chat completion call, and build a complete mini project (Text Summarizer). The process helped me understand how system and user messages affect the model’s output and how to control the format of the response to produce exactly three bullet points. At first, I was unsure about some of the API parameters and the client setup, but after experimenting with a few examples, the workflow became clear. I also learned how to structure my notebook properly so that it can be shared and documented in a GitHub repository.

"""